### ISSUE TITLE
UEVR profiles

### ISSUE THREAD

**Issue by peteostro** [Raicuparta/rai-pal#156] opened 2024-01-07 16:21 UTC
Right now it’s hard to find uevr profiles for games   Any way for Rai Pal to automatically launch UEVR with a recommended profile for the game you are launching?

**Comment by peteostro** [comment] 2024-01-07 16:25
You can find profiles in the profiles tab of this Google sheet https://docs.google.com/spreadsheets/d/1ZcjCQwzPOltaRZnpYU5_HPihEDareZq_0Ww1DZQ4USw/edit#gid=1224938259

**Comment by Raicuparta** [comment] 2024-01-07 16:28
That's in the plans, will happen once the flat2vr db is up and running

**Comment by Raicuparta** [comment] 2024-01-12 11:21
Just realized this is a duplicate of #110

**Closed by Raicuparta** 2024-01-12 11:21 UTC
Labels: enhancement
